# Generated by Django 5.2 on 2025-04-16 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryID', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('categoryName', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerID', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('companyName', models.CharField(max_length=200)),
                ('contactName', models.CharField(max_length=150)),
                ('contactTitle', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeID', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('titleOfCourtesy', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.')], max_length=10)),
                ('birthDate', models.DateTimeField()),
                ('hireDate', models.DateTimeField()),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('homePhone', models.CharField(blank=True, max_length=20, null=True)),
                ('extension', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reportsTo', models.PositiveIntegerField(blank=True, null=True)),
                ('photoPath', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTerritories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapi.employees')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('discount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderID', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('orderDate', models.DateTimeField()),
                ('requiredDate', models.DateTimeField()),
                ('shippedDate', models.DateTimeField()),
                ('freight', models.FloatField()),
                ('shipName', models.CharField(max_length=100)),
                ('shipAddress', models.CharField(max_length=255)),
                ('shipCity', models.CharField(blank=True, max_length=100, null=True)),
                ('shipRegion', models.CharField(blank=True, max_length=100, null=True)),
                ('shipPostalCode', models.CharField(blank=True, max_length=20, null=True)),
                ('shipCountry', models.CharField(blank=True, max_length=100, null=True)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapi.customers')),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapi.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productID', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('productName', models.CharField(max_length=200)),
                ('quantityPerUnit', models.CharField(max_length=100)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unitsInStock', models.PositiveIntegerField(default=0)),
                ('unitsOnOrder', models.PositiveIntegerField(default=0)),
                ('reorderLevel', models.PositiveIntegerField(default=0)),
                ('discontinued', models.PositiveIntegerField(default=0)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapi.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('regionID', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('regionDescription', models.CharField(choices=[('Eastern', 'Eastern'), ('Western', 'Western'), ('Northern', 'Northern'), ('Southern', 'Southern')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('shipperID', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('companyName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplierID', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('companyName', models.CharField(max_length=100)),
                ('contactName', models.CharField(max_length=100)),
                ('contactTitle', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('homePage', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Territories',
            fields=[
                ('territoryID', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('territoryDescription', models.TextField()),
                ('regionID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapi.regions')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='orderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapi.orders'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapi.products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipVia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapi.shippers'),
        ),
        migrations.AddField(
            model_name='products',
            name='supplierID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapi.suppliers'),
        ),
        migrations.AddField(
            model_name='employeeterritories',
            name='territoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminapi.territories'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetails',
            unique_together={('orderID', 'productID')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeterritories',
            unique_together={('employeeID', 'territoryID')},
        ),
    ]
